### DISCUSSION TITLE
List of available JupyterLite kernels?

### DISCUSSION THREAD

**Discussion by deeplook** [jupyterlite/jupyterlite#968] [Ideas]
I wondered which kernels are available for JupyterLite (other than those bundled with it) and looked into the documentation on https://jupyterlite.readthedocs.io/en/latest/index.html, but I don't see an explicit answer. Is it implicitly the list of kernel repos on https://github.com/jupyterlite/ or are there other Jupyter kernels? Are there othere kernels working on JupyterLite? Does anybody maintain an "awesome" such list (I haven't found any)? If there is a significant number maybe it's worth to put it into the documentation. Maybe even some flag on a list like https://github.com/jupyter/jupyter/wiki/Jupyter-kernels indicating if the respective kernel works with JupyterLite might be useful?

Also, is it fair/correct to assume that an existing Jupyter kernel does not install as-is in JupyterLite?

Thanks for any insights!

**Comment by jtpio** [comment]
> Also, is it fair/correct to assume that an existing Jupyter kernel does not install as-is in JupyterLite?

Right most of the existing kernels will *not* work as-is in JupyterLite.

But many Xeus kernels do work now. The JupyterLite demo site includes a couple of them: https://jupyterlite.github.io/demo/

There is also a Ruby kernel: https://github.com/kateinoigakukun/jupyterlite-ruby-kernel

Probably we could try to maintain a list of kernels on the docs page, but without any guarantee they would still work in the future.

**Reply by deeplook** [reply]
Thanks! I did not know about the Ruby one!

And while not being an advocate for R myself, I can see some people who would be delighted to see a R JupyterLite kernel. No idea about the feasibility, though...

**Reply by westurner** [reply]
Could the docs page just include from the wiki table in https://github.com/jupyter/jupyter/wiki.git repo?

**Comment by bollwyvl** [comment]
Yep: it seems unlikely there will be enough of them to make the case for a PyPI trove classifier (took a while to get JupyterLab proper, and we have _hundreds_ of related packages). We could _potentially_ get a JupyterLite classifier, as more of a "works with JupyterLite," but it wouldn't be package-related.

Failing being able to pass the buck entirely, having dealt with some of these issues on Language Server stuff, about the best we could do would be to allow an extension author to PR a (schema-constrained) data file, maybe as yaml/toml.

This could be built into the docs site which could fetch canonical data from upstream sources: otherwise stuff gets out of date real fast.

```yaml
# community/jupyterlite-robotkernel.yaml
pypi: jupyterlite-robotkernel
github:
  org: robots-from-jupyter
  repo: robotkernel
  branch: master
  path: lite/jupyterlite-robotkernel # optional
provides:
  kernel:
    languages:
      - robotframework
    extensions:
      - .robot
      - .resource
# conda-forge: not published here
# npm:  not published here
# gitlab: not published here
# bitbucket: nobody cares anymore
```
