### ISSUE TITLE
Accessing postgres database from python kernel

### ISSUE THREAD

**Issue by butsuri43** [jupyterlite/jupyterlite#1083]
### Problem
Accessing Postgres database from jupyterlite (pyodide). 

I would like to start a discussion what is currently possible and what are potential options for the future.

### Suggested Improvement
I have been experimenting with this and here is what I found:
- none- of the SQL libraries I tried worked. `psycopg2`, `py-postgresql`, `asyncpg` and `PyGreSQL` are not pure pythonic, so already the installation fails. `psycopg` installs without error, but fails on import (`ImportError: no pq wrapper available.`). `pg8000` also installs, but fails connecting raising error on execution of `socket.create_connection`. 
- the one way that works for me is to connect to the database through a REST API proxy that can be easily set-up with https://postgrest.org/en/stable/. Here is a minimal example that works for me:
  1) `docker-compose.yml` file for setting up an example database and the proxy-server:
      ```
      version: '3'
      services:
        server:
          image: postgrest/postgrest
          ports:
            - "3000:3000"
          environment:
            PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
            PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
            PGRST_DB_ANON_ROLE: web_anon
          depends_on:
            - db
        db:
          image: postgres
          ports:
            - "5432:5432"
          environment:
            POSTGRES_DB: app_db
            POSTGRES_USER: app_user
            POSTGRES_PASSWORD: password
          volumes:
            - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      ```
  2) `initdb.sql` file with database initial setup:
      ```
      create table todos (
        id serial primary key,
        done boolean not null default false,
        task text not null,
        due timestamptz
      );
      insert into todos (done,task) values
        (True,'finish tutorial 0'), (False,'pat self on back');
      create role web_anon nologin;
      grant select on todos to web_anon;
      ```
  3) Run `docker compose up` in the directory with both files to spin-up both servers
  4) Inside jupyterlite (e.g. the demo one: https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html) run:
      ```
      %pip install requests
      
      import requests
      import pyodide_http
      pyodide_http.patch_all() # see https://jupyterlite.readthedocs.io/en/latest/howto/content/python.html#fetching-remote-content
      x = requests.get('http://localhost:3000/todos')
      x.json()
      ```
  
  This method works, but requires using `postgrest` queries instead of standard SQL which is not so ideal...

Are there any options available?
