### ISSUE TITLE
Chrome crash "Aw, Snap!"

### ISSUE THREAD

**Issue by jvailius** [jupyterlite/jupyterlite#1359]
## Description

I several chrome crashes with "Aw, Snap!" Error code: 4. Sorry for the unspecific title but I have not more insight what the issue might be.

## Reproduce

It happens after opening 3 or more notebooks (containing some code but it just loads the kernel - no outputs present to render) or after repeatedly running several cells.

I have seen that memory usage for the chrome tab can very quickly grow close to 1GB. Maybe related. It may be a chrome issue when memory grows to fast in emscription - just guessing.

## Context

- jupyterlite-core: 0.3.0
- jupyterlite-xeus: 0.1.8
- Operating System and version: Debian bookworm
- Browser and version: Chrome

I build jupyterlite with defaults except `--XeusAddon.mount_jupyterlite_content=True` and the notebook folder set to read only (chmod 0444)

My environment.yml:

```yml
name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - matplotlib
  - requests
  - seaborn
  - xarray
  - jupyterlab_widgets
  - ipywidgets
  - pip
  - pip:
    - jlite/client  # a client site library
 ```
