### ISSUE TITLE
Update the Kernel docs

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#244]
Let's take a pass over the `docs/kernels` matrix and update with the features _actually_ supported? Probably need `comm` as well, now :laughing:
.
_Originally posted by @bollwyvl in https://github.com/jupyterlite/jupyterlite/issues/243#issuecomment-878243894_

**Comment by jtpio** [comment]
This would be useful especially to the Python kernel which has improved a lot recently.

cc @madhur-tandon @dsblank @martinRenou

**Comment by bollwyvl** [comment]
A missing thread from that component: we need to figure out how to keep that in check.

It's not part of the official kernelspec metadata, but heck, we own this implementation. I'd love to see us hoist as much off the `kernel_info` as possible to `package.json`, a la [`jyve`](https://github.com/deathbeds/jyve/blob/master/packages/jyve-kyrnel-p5-unsafe/package.json#L21) and add a section for capabilities. We can then use this data directly to generate the docs page.

So we might have:

```yaml
"jupyterlite": {
  "kernel": {
    "kernel_info": {...},
    "messages": ["execute_request", ..., "comm_open"]
  }
}
```
