### ISSUE TITLE
jupyter-lite.json and gitlab deployment

### ISSUE THREAD

**Issue by djangoliv** [jupyterlite/jupyterlite#597]
### Problem

I don't understand where I need to copy the jupyter-lite.json file in my gitlab deployment.
I tried to put it in the lab directory but the file is not taken into account.
Maybe I need to adapt my .gitlab-ci.yml

```
image: python:3.9
pages:
  stage: deploy
  before_script:
    - python -m pip install -r requirements.txt
  script:
    - jupyter lite build --contents contents --output-dir public
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - branch/default # the branch you want to publish

```

### Suggested Improvement

Perhaps the documentation is not clear enough on this point.

Regards
